[package]
name = "riptables"
version = "0.1.0"
authors = ["fewensa <fewensa@enoa.io>"]
edition = "2018"

[dependencies]
text-reader = "0.1"
regex = "0.2"
nix = "0.7.0"
string-builder = "0.2.0"
lazy_static = "0.2.8"

